### ISSUE TITLE
No display of AcoustID 

### ISSUE THREAD

**Issue by Alfge** [jesus2099/konami-command#686] opened 2022-06-09 22:18 UTC
Note by jesus2099
------------------------------

Duplicate of #596
**Workaround is to make this script near or at the end of your userscript list.**

---

mb. INLINE STUFF  version  2021.6.21
"Loading AcoustId" is displayed in the lower right corner but the AcoustID's are not displayed on the Overview web page for a release below each title.
The Hide/Show **AcoustIDs:** Button on the right side has no effect.

Firefox 101.0.1 (64-bit) + Violentmonkey v2.13.0 + Windows 10 64Bit

**Comment by a23bed** [comment] 2022-06-12 19:47
same issue no AcoustIDs and ISRC on Firefox 101.0.1 (64-bit) + Violentmonkeyv2.13.0 since server update
https://blog.metabrainz.org/2022/06/07/musicbrainz-server-update-2022-06-07/

on same system (Windows 7 x64)
Opera 88.0.4412.27 + Tampermonkey 4.15.6154
all works as before.

**Comment by jesus2099** [comment] 2022-06-12 20:56
duplicate of #596.

**Comment by jesus2099** [comment] 2022-06-13 07:25
**Workaround is to make this script near or at the end of your userscript list.**

Thanks for your report! and tell me if the workaround doesn't work for you.

**Closed by jesus2099** 2022-06-13 07:25 UTC
Labels: duplicate, server change, mb_INLINE-STUFF, react-hydrate

**Comment by Alfge** [comment] 2022-06-13 17:01
The workaround doesn't help for me

**Comment by jesus2099** [comment] 2022-06-14 12:49
Please tell in #596 if the quick fix worked for you. :)
