### ISSUE TITLE
issue with mb. INLINE STUFF 2015.11.2

### ISSUE THREAD

**Issue by Alfge** [jesus2099/konami-command#127] opened 2015-11-08 20:39 UTC
acoustids are not shown on the release -> overview page, with more mediums where the track list can be expand/collapse.
see: http://musicbrainz.org/release/3806ca30-2501-4e99-aad4-1600ad89f42e

**Comment by jesus2099** [comment] 2015-11-08 22:01
Thanks for the report, @Alfge. :)
But it’s a duplicate of #38.

**Closed by jesus2099** 2015-11-08 22:01 UTC
