### ISSUE TITLE
script idea (or addon to an existing one)

### ISSUE THREAD

**Issue by Lotheric** [jesus2099/konami-command#469] opened 2019-10-14 13:52 UTC
Hi Jesus,

It seems https://tickets.metabrainz.org/browse/MBS-3112 will go live (it's in beta right now) and while I'm glad for keyboard users they have their issue fixed, the solution proposed change the order of buttons for us mouse users. Do you thinnk it could be one of the options in your script (super mind control or a new script) to have the old buttons back at their original positions ?

- Lotheric

**Comment by jesus2099** [comment] 2019-10-14 14:32
Let's wait and see if we cannot just get used to the new button layout.
Thanks for your comment, I will keep it in mind when looking at #466.
Let me close it as duplicate of #466. 😅

**Closed by jesus2099** 2019-10-14 14:32 UTC
